package linkguard

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestExtractURLs(t *testing.T) {
	testCases := []struct {
		name     string
		text     string
		expected []string
	}{
		// Basic cases
		{
			name:     "no urls",
			text:     "this is a simple text.",
			expected: []string{},
		},
		{
			name:     "simple url",
			text:     "this is a simple text with a url https://example.com.",
			expected: []string{"https://example.com"},
		},
		{
			name:     "multiple urls",
			text:     "this is a simple text with a url https://example.com and http://google.com.",
			expected: []string{"https://example.com", "http://google.com"},
		},
		{
			name:     "url with www",
			text:     "this is a simple text with a url www.example.com.",
			expected: []string{"www.example.com"},
		},
		{
			name:     "url with path",
			text:     "this is a simple text with a url https://example.com/path.",
			expected: []string{"https://example.com/path"},
		},
		{
			name:     "url with query",
			text:     "this is a simple text with a url https://example.com/path?query=1.",
			expected: []string{"https://example.com/path?query=1"},
		},
		{
			name:     "url with fragment",
			text:     "this is a simple text with a url https://example.com/path?query=1#fragment.",
			expected: []string{"https://example.com/path?query=1#fragment"},
		},
		{
			name:     "markdown url",
			text:     "this is a simple text with a url [example](https://example.com).",
			expected: []string{"https://example.com"},
		},
		{
			name:     "strange url with random chars",
			text:     "click here: http://dkfjg-sdkjg.info/s-k_j.html?a=1&b=2",
			expected: []string{"http://dkfjg-sdkjg.info/s-k_j.html?a=1&b=2"},
		},
		{
			name:     "url in html",
			text:     `here is a link <a href="https://example.com/foo">click me</a>`,
			expected: []string{"https://example.com/foo"},
		},
		{
			name:     "url in html comments",
			text:     `<!-- check this out https://example.com/comment -->`,
			expected: []string{"https://example.com/comment"},
		},
		{
			name:     "url with percent encoding",
			text:     `https://example.com/search?q=%20hello%20world`,
			expected: []string{"https://example.com/search?q=%20hello%20world"},
		},
		{
			name: "mixed content",
			text: `
				Hello, please check this link: https://important-update.com/login.
				Also, see [our docs](http://docs.example.com/getting-started).
				<!-- ignore this: https://internal-dev.net -->
				And finally, a www link: www.google.com/search?q=test.
			`,
			expected: []string{
				"https://important-update.com/login",
				"http://docs.example.com/getting-started",
				"https://internal-dev.net",
				"www.google.com/search?q=test",
			},
		},
		{
			name:     "url with multiple subdomains",
			text:     "a url with multiple subdomains https://sub1.sub2.sub3.example.com",
			expected: []string{"https://sub1.sub2.sub3.example.com"},
		},
		{
			name:     "url with many 'w's",
			text:     "a strange url with many 'w's wwwwwwwww.example.com",
			expected: []string{"wwwwwwwww.example.com"},
		},
		{
			name:     "url with dots in path",
			text:     "a url with dots in path http://example.com/../../../etc/passwd",
			expected: []string{"http://example.com/../../../etc/passwd"},
		},
		// Phishing and obfuscated URLs
		{
			name:     "ip address url",
			text:     "access your account at http://192.168.1.1/login.php",
			expected: []string{"http://192.168.1.1/login.php"},
		},
		{
			name:     "url with port",
			text:     "go to http://example.com:8080",
			expected: []string{"http://example.com:8080"},
		},
		{
			name:     "homograph attack",
			text:     "visit https://microsоft.com, not microsoft.com",
			expected: []string{"https://microsоft.com", "microsoft.com"},
		},
		{
			name:     "url shortener",
			text:     "here is the link: https://bit.ly/3rXYZ",
			expected: []string{"https://bit.ly/3rXYZ"},
		},
		{
			name:     "url with @ symbol",
			text:     "go to https://example.com@google.com",
			expected: []string{"https://example.com@google.com"},
		},
		// False positives
		{
			name:     "coordinates",
			text:     "The location is 38.8977° N, 77.0365° W.",
			expected: []string{},
		},
		{
			name:     "decimal number",
			text:     "the value is 123.45",
			expected: []string{},
		},
		{
			name:     "number with unit",
			text:     "the distance is 35.9km",
			expected: []string{},
		},
		{
			name:     "version number",
			text:     "using version 1.2.3",
			expected: []string{},
		},
		{
			name:     "sentence ending with a dot",
			text:     "this is a test.",
			expected: []string{},
		},
		{
			name:     "email address",
			text:     "contact me at test@example.com",
			expected: []string{},
		},
		// More edge cases
		{
			name:     "url in quotes",
			text:     `here is a link "https://example.com"`,
			expected: []string{"https://example.com"},
		},
		{
			name:     "url in parentheses",
			text:     "here is a link (https://example.com)",
			expected: []string{"https://example.com"},
		},
		{
			name:     "url with special chars in path",
			text:     "https://example.com/a-b_c~d!e*f'g,h",
			expected: []string{"https://example.com/a-b_c~d!e*f'g,h"},
		},
		{
			name:     "url with trailing slash",
			text:     "https://example.com/path/",
			expected: []string{"https://example.com/path/"},
		},
		{
			name:     "just a domain",
			text:     "check example.com for more info",
			expected: []string{"example.com"},
		},
		{
			name:     "domain with hyphen",
			text:     "go to my-domain.com",
			expected: []string{"my-domain.com"},
		},
		{
			name:     "url with numbers in domain",
			text:     "visit 123-example.com",
			expected: []string{"123-example.com"},
		},
		{
			name:     "url in uppercase",
			text:     "HTTPS://EXAMPLE.COM",
			expected: []string{"HTTPS://EXAMPLE.COM"},
		},
		{
			name:     "url without protocol in markdown",
			text:     "[example](www.example.com)",
			expected: []string{"www.example.com"},
		},
		{
			name:     "ftp url",
			text:     "download from ftp://example.com/file.zip",
			expected: []string{"ftp://example.com/file.zip"},
		},
		{
			name:     "file url",
			text:     "open this file:///Users/test/file.html",
			expected: []string{"file:///Users/test/file.html"},
		},
		{
			name:     "url with very long subdomain",
			text:     "http://this.is.a.very.long.subdomain.example.com",
			expected: []string{"http://this.is.a.very.long.subdomain.example.com"},
		},
		// 200+ more test cases
		{name: "Simple HTTP", text: "http://example.com", expected: []string{"http://example.com"}},
		{name: "Simple HTTPS", text: "https://example.com", expected: []string{"https://example.com"}},
		{name: "Simple WWW", text: "www.example.com", expected: []string{"www.example.com"}},
		{name: "Simple FTP", text: "ftp://example.com", expected: []string{"ftp://example.com"}},
		{name: "Domain with hyphen", text: "my-domain.com", expected: []string{"my-domain.com"}},
		{name: "URL with path", text: "https://example.com/path/to/resource", expected: []string{"https://example.com/path/to/resource"}},
		{name: "URL with query string", text: "https://example.com?key=value", expected: []string{"https://example.com?key=value"}},
		{name: "URL with fragment", text: "https://example.com#section", expected: []string{"https://example.com#section"}},
		{name: "URL with port", text: "http://example.com:8080", expected: []string{"http://example.com:8080"}},
		{name: "URL with IP address", text: "http://192.168.0.1", expected: []string{"http://192.168.0.1"}},
		{name: "URL in sentence", text: "Check this link: https://example.com.", expected: []string{"https://example.com"}},
		{name: "Multiple URLs in sentence", text: "Links: http://one.com and http://two.com.", expected: []string{"http://one.com", "http://two.com"}},
		{name: "URL in parentheses", text: "(https://example.com)", expected: []string{"https://example.com"}},
		{name: "URL in quotes", text: "\"https://example.com\"", expected: []string{"https://example.com"}},
		{name: "Markdown link", text: "[example](https://example.com)", expected: []string{"https://example.com"}},
		{name: "HTML link", text: "<a href=\"https://example.com\">example</a>", expected: []string{"https://example.com"}},
		{name: "URL with special chars in query", text: "https://example.com?q=a,b;c|d", expected: []string{"https://example.com?q=a,b;c|d"}},
		{name: "Phishing: multiple www", text: "wwwwww.example.com", expected: []string{"wwwwww.example.com"}},
		{name: "Phishing: path traversal", text: "http://example.com/../../../etc/passwd", expected: []string{"http://example.com/../../../etc/passwd"}},
		{name: "Phishing: homograph", text: "https://microsоft.com", expected: []string{"https://microsоft.com"}},
		{name: "Phishing: URL with @", text: "https://user@example.com", expected: []string{"https://user@example.com"}},
		{name: "No URL: simple text", text: "This is a simple sentence.", expected: []string{}},
		{name: "No URL: coordinates", text: "Location: 40.7128, -74.0060", expected: []string{}},
		{name: "No URL: decimal number", text: "Value: 123.45", expected: []string{}},
		{name: "No URL: version number", text: "Version 1.2.3", expected: []string{}},
		{name: "No URL: number with unit", text: "Distance: 35.9km", expected: []string{}},
		{name: "No URL: email", text: "contact test@example.com", expected: []string{"test@example.com"}},
		{name: "URL with subdomain", text: "https://sub.example.com", expected: []string{"https://sub.example.com"}},
		{name: "URL with multiple subdomains", text: "https://a.b.c.example.com", expected: []string{"https://a.b.c.example.com"}},
		{name: "URL with uppercase", text: "HTTPS://EXAMPLE.COM", expected: []string{"HTTPS://EXAMPLE.COM"}},
		{name: "URL with mixed case", text: "HttpS://ExAmPlE.cOm", expected: []string{"HttpS://ExAmPlE.cOm"}},
		{name: "URL with long path", text: "https://example.com/a/b/c/d/e/f/g", expected: []string{"https://example.com/a/b/c/d/e/f/g"}},
		{name: "URL with file extension", text: "https://example.com/file.html", expected: []string{"https://example.com/file.html"}},
		{name: "URL with trailing slash", text: "https://example.com/path/", expected: []string{"https://example.com/path/"}},
		{name: "URL with plus in query", text: "https://example.com/search?q=a+b", expected: []string{"https://example.com/search?q=a+b"}},
		{name: "URL with percent encoding", text: "https://example.com/search?q=%20", expected: []string{"https://example.com/search?q=%20"}},
		{name: "URL in HTML comment", text: "<!-- https://example.com -->", expected: []string{"https://example.com"}},
		{name: "URL with international characters", text: "http://例子.测试", expected: []string{"http://例子.测试"}},
		{name: "Phishing: login keyword", text: "https://example.com/login", expected: []string{"https://example.com/login"}},
		{name: "Phishing: verify keyword", text: "https://example.com/verify-account", expected: []string{"https://example.com/verify-account"}},
		{name: "Phishing: suspicious TLD .xyz", text: "http://scam.xyz", expected: []string{"http://scam.xyz"}},
		{name: "Phishing: suspicious TLD .top", text: "http://win-prize.top", expected: []string{"http://win-prize.top"}},
		{name: "URL inside another string", text: "The string is 'https://example.com'", expected: []string{"https://example.com"}},
		{name: "URL at the beginning of text", text: "https://example.com is a link.", expected: []string{"https://example.com"}},
		{name: "URL at the end of text", text: "A link is https://example.com", expected: []string{"https://example.com"}},
		{name: "URL with underscore in domain", text: "http://my_site.com", expected: []string{"http://my_site.com"}},
		{name: "URL with underscore in path", text: "http://example.com/my_path", expected: []string{"http://example.com/my_path"}},
		{name: "No URL: sentence with 'a.m.'", text: "It's 10 a.m.", expected: []string{}},
		{name: "No URL: sentence with 'e.g.'", text: "For example, e.g., a test.", expected: []string{}},
		{name: "URL with comma", text: "Check https://example.com, it's great.", expected: []string{"https://example.com"}},
		{name: "URL with semicolon", text: "Visit https://example.com; then do something else.", expected: []string{"https://example.com"}},
		{name: "URL with IPv6", text: "http://[2001:db8::1]", expected: []string{"http://[2001:db8::1]"}},
		{name: "URL with IPv6 and port", text: "http://[2001:db8::1]:8080", expected: []string{"http://[2001:db8::1]:8080"}},
		{name: "URL with username and password", text: "https://user:pass@example.com", expected: []string{"https://user:pass@example.com"}},
		{name: "URL in multi-line text", text: "line 1\nhttps://example.com\nline 3", expected: []string{"https://example.com"}},
		{name: "Phishing: deceptive subdomain", text: "https://login.microsoft.com.security-alert.com", expected: []string{"https://login.microsoft.com.security-alert.com"}},
		{name: "Phishing: random string", text: "http://asdfghjkl.com", expected: []string{"http://asdfghjkl.com"}},
		{name: "Phishing: URL shortener", text: "https://tinyurl.com/y1x2z3", expected: []string{"https://tinyurl.com/y1x2z3"}},
		{name: "No URL: file path", text: "C:\\Users\\Test\\file.txt", expected: []string{}},
		{name: "No URL: scientific notation", text: "Value: 1.23e-4", expected: []string{}},
		{name: "URL with query and fragment", text: "https://example.com?q=1#s=2", expected: []string{"https://example.com?q=1#s=2"}},
		{name: "URL with escaped chars", text: "https://example.com/path%20with%20spaces", expected: []string{"https://example.com/path%20with%20spaces"}},
		{name: "URL in XML/HTML attribute", text: "<tag value=\"https://example.com\"/>", expected: []string{"https://example.com"}},
		{name: "URL in CSS", text: "background-image: url(https://example.com/bg.png)", expected: []string{"https://example.com/bg.png"}},
		{name: "Phishing: directory traversal", text: "https://example.com/..%2f..%2f..%2f/etc/passwd", expected: []string{"https://example.com/..%2f..%2f..%2f/etc/passwd"}},
		{name: "Phishing: TLD .zip", text: "http://important-docs.zip", expected: []string{"http://important-docs.zip"}},
		{name: "No URL: simple time", text: "The time is 12:30.", expected: []string{}},
		{name: "URL with numbers only in domain", text: "http://12345.com", expected: []string{"http://12345.com"}},
		{name: "URL with .co.uk", text: "http://example.co.uk", expected: []string{"http://example.co.uk"}},
		{name: "URL with .org", text: "https://example.org", expected: []string{"https://example.org"}},
		{name: "URL with .net", text: "www.example.net", expected: []string{"www.example.net"}},
		{name: "URL with .io", text: "https://example.io", expected: []string{"https://example.io"}},
		{name: "URL with .gov", text: "https://example.gov", expected: []string{"https://example.gov"}},
		{name: "URL with .edu", text: "http://example.edu", expected: []string{"http://example.edu"}},
		{name: "URL with .info", text: "example.info", expected: []string{"example.info"}},
		{name: "URL with .biz", text: "example.biz", expected: []string{"example.biz"}},
		{name: "URL with .tv", text: "example.tv", expected: []string{"example.tv"}},
		{name: "URL with country code TLD", text: "http://example.de", expected: []string{"http://example.de"}},
		{name: "URL with long TLD", text: "http://example.international", expected: []string{"http://example.international"}},
		{name: "No URL: chemical formula", text: "Water is H2O.", expected: []string{}},
		{name: "URL followed by punctuation", text: "https://example.com!", expected: []string{"https://example.com"}},
		{name: "URL followed by question mark", text: "Is this the link: https://example.com?", expected: []string{"https://example.com"}},
		{name: "URL in brackets", text: "[https://example.com]", expected: []string{"https://example.com"}},
		{name: "URL in curly braces", text: "{https://example.com}", expected: []string{"https://example.com"}},
		{name: "URL with non-ASCII chars", text: "http://例子.测试/路径", expected: []string{"http://例子.测试/路径"}},
		{name: "Phishing: fake 'secure' keyword", text: "https://secure-login-example.com", expected: []string{"https://secure-login-example.com"}},
		{name: "Phishing: excessive subdomains", text: "http://a.b.c.d.e.f.g.h.example.com", expected: []string{"http://a.b.c.d.e.f.g.h.example.com"}},
		{name: "No URL: acronym with dots", text: "U.S.A. is a country.", expected: []string{}},
		{name: "URL with ampersand in path", text: "https://example.com/path&other", expected: []string{"https://example.com/path&other"}},
		{name: "URL with equals in path", text: "https://example.com/path=value", expected: []string{"https://example.com/path=value"}},
		{name: "URL with comma in path", text: "https://example.com/a,b,c", expected: []string{"https://example.com/a,b,c"}},
		{name: "URL with semicolon in path", text: "https://example.com/a;b;c", expected: []string{"https://example.com/a;b;c"}},
		{name: "URL with parentheses in path", text: "https://example.com/a(b)c", expected: []string{"https://example.com/a(b)c"}},
		{name: "URL with apostrophe in path", text: "https://example.com/it's-a-path", expected: []string{"https://example.com/it's-a-path"}},
		{name: "URL with space (needs encoding)", text: "https://example.com/a b", expected: []string{"https://example.com/a"}},
		{name: "Phishing: using IP in hex", text: "http://0xc0.0xa8.0x00.0x01", expected: []string{"http://0xc0.0xa8.0x00.0x01"}},
		{name: "Phishing: using IP in octal", text: "http://0300.0250.0000.0001", expected: []string{"http://0300.0250.0000.0001"}},
		{name: "No URL: price", text: "The price is $19.99.", expected: []string{}},
		{name: "No URL: date", text: "The date is 2024.01.01.", expected: []string{}},
		{name: "URL with only scheme and domain", text: "https://example.com", expected: []string{"https://example.com"}},
		{name: "URL with only domain", text: "example.com", expected: []string{"example.com"}},
		{name: "URL with very long query string", text: "https://example.com?long_query=... (200+ chars)", expected: []string{"https://example.com?long_query=..."}},
		{name: "URL with very long fragment", text: "https://example.com#long_fragment=... (200+ chars)", expected: []string{"https://example.com#long_fragment=..."}},
		{name: "URL inside a long text", text: "Lorem ipsum... https://example.com ...dolor sit amet.", expected: []string{"https://example.com"}},
		{name: "Phishing: .tk TLD", text: "http://free-stuff.tk", expected: []string{"http://free-stuff.tk"}},
		{name: "Phishing: .ml TLD", text: "http://your-bank.ml", expected: []string{"http://your-bank.ml"}},
		{name: "Phishing: .ga TLD", text: "http://account-update.ga", expected: []string{"http://account-update.ga"}},
		{name: "URL with two-letter TLD", text: "http://example.io", expected: []string{"http://example.io"}},
		{name: "URL with new gTLD", text: "http://example.club", expected: []string{"http://example.club"}},
		{name: "URL with non-latin characters in path", text: "https://example.com/你好", expected: []string{"https://example.com/你好"}},
		{name: "No URL: book title with numbers", text: "Read 'Chapter 1.2'.", expected: []string{}},
		{name: "URL with exclamation mark in query", text: "https://example.com?q=wow!", expected: []string{"https://example.com?q=wow!"}},
		{name: "URL with dollar sign in query", text: "https://example.com?price=$100", expected: []string{"https://example.com?price=$100"}},
		{name: "URL with asterisk in query", text: "https://example.com?search=*", expected: []string{"https://example.com?search=*"}},
		{name: "URL with colon in path", text: "https://example.com/path:value", expected: []string{"https://example.com/path:value"}},
		{name: "Phishing: fake URL in plain text", text: "This is not a link: example dot com", expected: []string{}},
		{name: "Phishing: unicode full-width characters", text: "ｈｔｔｐｓ：／／ｅｘａｍｐｌｅ．ｃｏｍ", expected: []string{"ｈｔｔｐｓ：／／ｅｘａｍｐｌｅ．ｃｏｍ"}},
		{name: "No URL: list of numbers", text: "1. 2. 3. 4. 5.", expected: []string{}},
		{name: "URL with mixed protocols", text: "From http://a.com to https://b.com", expected: []string{"http://a.com", "https://b.com"}},
		{name: "URL with trailing dots", text: "https://example.com...", expected: []string{"https://example.com"}},
		{name: "URL with hashbang", text: "https://example.com/#!/path", expected: []string{"https://example.com/#!/path"}},
		{name: "URL in JS code", text: "var url = 'https://example.com';", expected: []string{"https://example.com"}},
		{name: "Phishing: using a known brand in subdomain", text: "https://google.com.example.com", expected: []string{"https://google.com.example.com"}},
		{name: "Phishing: URL ending in .com.br", text: "http://example.com.br", expected: []string{"http://example.com.br"}},
		{name: "No URL: measurement", text: "The size is 1.5m.", expected: []string{}},
		{name: "No URL: phone number", text: "Call 123-456-7890.", expected: []string{}},
		{name: "URL with mixed case query", text: "https://example.com?Key=Value", expected: []string{"https://example.com?Key=Value"}},
		{name: "URL with repeated query params", text: "https://example.com?a=1&a=2", expected: []string{"https://example.com?a=1&a=2"}},
		{name: "URL in a file path like string", text: "/path/to/https://example.com", expected: []string{"https://example.com"}},
		{name: "Phishing: url with urgent words", text: "https://example.com/urgent-action-required", expected: []string{"https://example.com/urgent-action-required"}},
		{name: "Phishing: data URL", text: "data:text/html,<script>alert(1)</script>", expected: []string{"data:text/html,<script>alert(1)</script>"}},
		{name: "No URL: a simple math expression", text: "2 * 3.14 * r", expected: []string{}},
		{name: "URL with single letter domain", text: "http://a.com", expected: []string{"http://a.com"}},
		{name: "URL with single letter subdomain", text: "http://a.example.com", expected: []string{"http://a.example.com"}},
		{name: "URL with single letter path", text: "http://example.com/a", expected: []string{"http://example.com/a"}},
		{name: "URL with single letter query", text: "http://example.com?a=b", expected: []string{"http://example.com?a=b"}},
		{name: "URL with single letter fragment", text: "http://example.com#a", expected: []string{"http://example.com#a"}},
		{name: "URL with no scheme but with path", text: "example.com/path", expected: []string{"example.com/path"}},
		{name: "URL with no scheme but with query", text: "example.com?q=1", expected: []string{"example.com?q=1"}},
		{name: "URL with no scheme but with fragment", text: "example.com#s1", expected: []string{"example.com#s1"}},
		{name: "Phishing: excessive percent encoding", text: "http://example.com/%25%32%35", expected: []string{"http://example.com/%25%32%35"}},
		{name: "Phishing: mixed scripts (Latin and Cyrillic)", text: "http://еxample.com", expected: []string{"http://еxample.com"}},
		{name: "No URL: chemical element", text: "Symbol for gold is Au.", expected: []string{}},
		{name: "No URL: legal text with sections", text: "See section 1.2.a.", expected: []string{}},
		{name: "URL with tilde", text: "http://example.com/~user", expected: []string{"http://example.com/~user"}},
		{name: "URL with ` at the end", text: "https://example.com`", expected: []string{"https://example.com"}},
		{name: "URL with | in query", text: "https://example.com?p1|p2", expected: []string{"https://example.com?p1|p2"}},
		{name: "URL with ^ in query", text: "https://example.com?p1^p2", expected: []string{"https://example.com?p1^p2"}},
		{name: "URL with { } in query", text: "https://example.com?p={v}", expected: []string{"https://example.com?p={v}"}},
		{name: "URL with [ ] in query", text: "https://example.com?p=[v]", expected: []string{"https://example.com?p=[v]"}},
		{name: "Phishing: URL with invisible characters", text: "http://example.com/\u200b", expected: []string{"http://example.com/\u200b"}},
		{name: "Phishing: misleading link text", text: "[http://google.com](http://evil.com)", expected: []string{"http://google.com", "http://evil.com"}},
		{name: "No URL: empty string", text: "", expected: []string{}},
		{name: "No URL: string with only spaces", text: "   ", expected: []string{}},
		{name: "URL with only numbers and TLD", text: "12345.com", expected: []string{"12345.com"}},
		{name: "URL with multiple query params", text: "https://example.com?a=1&b=2&c=3", expected: []string{"https://example.com?a=1&b=2&c=3"}},
		{name: "URL with file protocol", text: "file:///path/to/file", expected: []string{"file:///path/to/file"}},
		{name: "URL with mailto protocol", text: "mailto:test@example.com", expected: []string{"mailto:test@example.com"}},
		{name: "URL with tel protocol", text: "tel:123-456-7890", expected: []string{"tel:123-456-7890"}},
		{name: "URL with sms protocol", text: "sms:+11234567890", expected: []string{"sms:+11234567890"}},
		{name: "URL with magnet protocol", text: "magnet:?xt=urn:btih:...", expected: []string{"magnet:?xt=urn:btih:..."}},
		{name: "Phishing: multiple dots in domain", text: "http://example...com", expected: []string{"http://example...com"}},
		{name: "Phishing: hyphen at the end of subdomain", text: "http://sub-.example.com", expected: []string{"http://sub-.example.com"}},
		{name: "No URL: stock ticker", text: "AAPL is up 1.5%.", expected: []string{}},
		{name: "No URL: temperature", text: "It is 25.5°C.", expected: []string{}},
		{name: "URL with port 443 on http", text: "http://example.com:443", expected: []string{"http://example.com:443"}},
		{name: "URL with port 80 on https", text: "https://example.com:80", expected: []string{"https://example.com:80"}},
		{name: "URL in XML file", text: "<?xml version=\"1.0\"?><link>https://example.com</link>", expected: []string{"https://example.com"}},
		{name: "URL in JSON file", text: "{\"url\": \"https://example.com\"}", expected: []string{"https://example.com"}},
		{name: "Phishing: URL with Punycode", text: "http://xn--e1afmkfd.xn--p1ai", expected: []string{"http://xn--e1afmkfd.xn--p1ai"}},
		{name: "Phishing: URL with mixed case and numbers", text: "hTTp://ExAmPlE123.cOm", expected: []string{"hTTp://ExAmPlE123.cOm"}},
		{name: "No URL: ISBN number", text: "ISBN 978-3-16-148410-0", expected: []string{}},
		{name: "URL surrounded by non-space characters", text: "text-https://example.com-text", expected: []string{"https://example.com-text"}},
		{name: "URL with only TLD", text: ".com", expected: []string{}},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			assert.ElementsMatch(t, tc.expected, ExtractURLs(tc.text))
		})
	}
}
